name: Variables & Secrets Demo (3)

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Variable
        run: echo "Variable: ${{ vars.MY_VAR }}"
      
      - name: Use Secret
        run: echo "Secret is set: ${{ secrets.MY_SECRET != '' }}"
        env:
          SECRET: ${{ secrets.MY_SECRET }}
